name: Run X Auto Post Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
