name: Notion Insert Production

on:
  workflow_dispatch:

jobs:
  insert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Notion insert
        run: |
          set -e
          echo "本番のNotion登録を実行中..."
          python3 scripts/notion_insert.py
          echo "Notion登録（本番）が成功しました"

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Notion登録（本番）が成功しました",
              "attachments": [
                {
                  "color": "good",
                  "text": "Notion登録（本番）が成功しました"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
