name: Notion Insert Mock

on:
  workflow_dispatch:

jobs:
  insert_mock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required Python packages
        run: |
          set -e
          pip install feedparser deep-translator requests python-dotenv notion-client beautifulsoup4

      - name: Run mock Notion insert
        run: |
          set -e
          echo "モックのNotion登録を実行中..."
          python scripts/notion_mock.py
          echo "Notion登録（モック）が成功しました"

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Notion登録（モック）が成功しました",
              "attachments": [
                {
                  "color": "good",
                  "text": "Notion登録（モック）が成功しました"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
