name: Notion Insert Prod

on:
  workflow_dispatch:
  schedule:
    - cron: "2 * * * *"

concurrency:
  group: notion-insert-prod
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  insert_prod:
    runs-on: ubuntu-latest
    env:
      RUN_START_MSG: "=== 本番実行開始 ==="
      RUN_DOING_MSG: "Notion登録を実行中..."
      RUN_SUCCESS_MSG: "Notion登録（本番）が成功しました"
      RUN_END_MSG: "=== 本番実行終了 ==="
      SLACK_SUCCESS_TEXT: "✅ Notion登録（本番）が成功しました"
      SLACK_FAILURE_TEXT: "❌ Notion登録（本番）が失敗しました（依存/Secrets/実行を確認してください）"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install & verify Python dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          python -m pip install feedparser deep-translator requests beautifulsoup4
          python - <<'PY'
          import sys, pkgutil
          required = ["feedparser","deep_translator","requests","bs4"]
          missing = [m for m in required if pkgutil.find_loader(m) is None]
          if missing:
              print("Missing modules:", ", ".join(missing), file=sys.stderr)
              sys.exit(1)
          PY

      - name: Validate required secrets for PROD
        env:
          _RSS_URL: ${{ secrets.RSS_URL }}
          _NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          _NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          _SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -e
          for s in _RSS_URL _NOTION_API_KEY _NOTION_DATABASE_ID _SLACK_WEBHOOK_URL; do
            if [ -z "${!s}" ]; then
              echo "❌ Required secret is missing: ${s#_}" >&2
              exit 1
            fi
          done
          echo "✅ All required secrets for PROD are present. (DEEPL_API_KEY is optional)"

      - name: Backup repository to local-like storage
        run: |
          set -e
          BACKUP_DIR="local_backups/$(date +'%Y%m%d_%H%M%S')"
          mkdir -p "$BACKUP_DIR"
          rsync -av --exclude "local_backups" ./ "$BACKUP_DIR"/
          echo "✅ Backup completed at $BACKUP_DIR"

      - name: Python syntax check (preflight)
        run: |
          set -e
          python -m py_compile scripts/notion_insert.py
          echo "✅ Syntax OK"

      - name: Run production Notion insert
        env:
          RSS_URL: ${{ secrets.RSS_URL }}
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -e
          echo "$RUN_START_MSG"
          echo "$RUN_DOING_MSG"
          python scripts/notion_insert.py
          echo "$RUN_SUCCESS_MSG"
          echo "$RUN_END_MSG"

      - name: Send Slack notification (success)
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            { "text": "${{ env.SLACK_SUCCESS_
