name: Notion Insert Mock

on:
  workflow_dispatch:

jobs:
  notion_insert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y jq

      - name: Run Notion Insert Script (Mock)
        id: run_script
        shell: bash
        run: |
          set +e
          python scripts/notion_insert.py > script_output.log 2>&1
          exit_code=$?
          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"

          if [ $exit_code -ne 0 ]; then
            echo "status=failed" >> "$GITHUB_OUTPUT"
            error_json=$(jq -Rs '.' < script_output.log)
            echo "error_json=$error_json" >> "$GITHUB_OUTPUT"
          else
            echo "status=success" >> "$GITHUB_OUTPUT"
            echo 'error_json=""' >> "$GITHUB_OUTPUT"
          fi
          set -e

      - name: Prepare Slack Payload
        id: prepare_slack
        shell: bash
        env:
          STATUS: ${{ steps.run_script.outputs.status }}
          ERROR_JSON: ${{ steps.run_script.outputs.error_json }}
        run: |
          jq -n \
            --arg status "$STATUS" \
            --arg error_raw "$ERROR_JSON" '
              ($status == "success" ? "good" : "danger") as $color
              | ( if $status == "success"
                  then "Notion登録（モック）が成功しました"
                  else ("Notion登録（モック）が失敗しました\n\nエラー内容:\n```" + ($error_raw | fromjson) + "```")
                end ) as $message
              | {
                  text: ("モックワークフロー実行結果: " + $status),
                  attachments: [
                    {
                      color: $color,
                      text: $message
                    }
                  ]
                }
            ' > slack_payload.json

      - name: Send Slack Notification
        if: always()
        run: |
          cat slack_payload.json | slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
