name: Post to X Prod

on:
  workflow_dispatch:
  schedule:
    # 毎時02分
    - cron: "2 * * * *"

concurrency:
  group: post-to-x-prod
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  post_to_x_prod:
    runs-on: ubuntu-latest
    env:
      RUN_START_MSG: "=== 本番投稿実行開始 ==="
      RUN_DOING_MSG: "本番投稿処理中..."
      RUN_SUCCESS_MSG: "✅ 本番投稿が成功しました"
      RUN_END_MSG: "=== 本番投稿実行終了 ==="
      SLACK_SUCCESS_TEXT: "✅ X投稿（本番）が成功しました"
      SLACK_FAILURE_TEXT: "❌ X投稿（本番）が失敗しました（依存/Secrets/実行を確認してください）"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies from requirements.txt
        run: |
          set -e
          python -m pip install --upgrade pip
          if [ ! -f requirements.txt ]; then
            echo "❌ requirements.txt が見つかりません。依存関係を定義してください。" >&2
            exit 1
          fi
          python -m pip install -r requirements.txt

      - name: Verify required Python modules
        run: |
          set -e
          python - <<'PY'
          import sys, pkgutil
          required = ["requests","feedparser","deep_translator","bs4","tweepy"]
          missing = [m for m in required if pkgutil.find_loader(m) is None]
          if missing:
              print("Missing modules:", ", ".join(missing), file=sys.stderr)
              sys.exit(1)
          PY
          echo "✅ All required Python modules are installed."

      - name: Validate required secrets (X / Notion / Slack)
        env:
          _X_API_KEY: ${{ secrets.X_API_KEY }}
          _X_API_SECRET: ${{ secrets.X_API_SECRET }}
          _X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          _X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          _SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          _NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          _NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          set -e
          for s in _X_API_KEY _X_API_SECRET _X_ACCESS_TOKEN _X_ACCESS_SECRET _SLACK_WEBHOOK_URL _NOTION_API_KEY _NOTION_DATABASE_ID; do
            if [ -z "${!s}" ]; then
              echo "❌ Required secret is missing: ${s#_}" >&2
              exit 1
            fi
            # 簡易長さチェック
            if [ ${#${!s}} -lt 10 ]; then
              echo "❌ Secret seems too short: ${s#_}" >&2
              exit 1
            fi
          done
          echo "✅ All required secrets for PROD are present."

      - name: Backup repository to local-like storage
        run: |
          set -e
          BACKUP_DIR="local_backups/$(date +'%Y%m%d_%H%M%S')"
          mkdir -p "$BACKUP_DIR"
          rsync -av --exclude "local_backups" ./ "$BACKUP_DIR"/
          echo "✅ Backup completed at $BACKUP_DIR"

      - name: Python syntax check (preflight)
        run: |
          set -e
          python -m py_compile scripts/post_to_x.py
          echo "✅ Syntax OK"

      - name: Run production X post
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          # DRY_RUN を有効化したい場合は、手動実行時に true を渡す
          DRY_RUN: ${{ inputs.DRY_RUN }}
        run: |
          set -e
          echo "$RUN_START_MSG"
          echo "$RUN_DOING_MSG"
          python scripts/post_to_x.py
          echo "$RUN_SUCCESS_MSG"
          echo "$RUN_END_MSG"

      - name: Send Slack notification (success)
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            { "text": "${{ env.SLACK_SUCCESS_TEXT }}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send Slack notification (failure)
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            { "text": "${{ env.SLACK_FAILURE_TEXT }}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
